"""Added age column to users

Revision ID: c64d3b757c57
Revises: 38b08c49d230
Create Date: 2024-04-28 12:41:05.693157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64d3b757c57'
down_revision = '38b08c49d230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_message_parent_id', 'message', ['parent_id'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###

