"""Added timetable and enrollments columns and changed message.image_url to 'String' in order to manage image urls

Revision ID: f7df835a3302
Revises: 8319e1697882
Create Date: 2024-05-15 08:21:45.824746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7df835a3302'
down_revision = '8319e1697882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timetable', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('enrollments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('enrollments')
        batch_op.drop_column('timetable')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
